name: Generate zip files and Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 --match 'v*' || echo "v1.0")
        echo "tag=$latest_tag" >> $GITHUB_ENV
    
    - name: Set new version
      id: set_version
      run: |
        latest_tag=${{ env.tag }}
        echo "Latest tag: $latest_tag"
        version=${latest_tag#v}
        IFS='.' read -r -a version_parts <<< "$version"
        version_parts[1]=$((version_parts[1] + 1))
        new_version="v${version_parts[0]}.${version_parts[1]}"
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"
    
    - name: Generate a zip file of index.py
      run: zip index.zip index.py

    - name: Generate a zip file of huaweicloudsdkcce folder
      run: zip -r huaweicloudsdkcce.zip dependencies/huaweicloudsdkcce

    - name: Generate a zip file of huaweicloudsdkecs folder
      run: zip -r huaweicloudsdkecs.zip dependencies/huaweicloudsdkecs

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        gh release create ${{ env.new_version }} index.zip huaweicloudsdkcce.zip huaweicloudsdkecs.zip --title "Release ${{ env.new_version }}" --notes "Automated release of index.py, huaweicloudsdkcce folder, and huaweicloudsdkecs folder"
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
