name: Generate a zip file of index-preview.py and Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 --match 'v*' || echo "v1.0")
        echo "tag=$latest_tag" >> $GITHUB_ENV
    
    - name: Set new version
      id: set_version
      run: |
        latest_tag=${{ env.tag }}
        echo "Latest tag: $latest_tag"
        version=${latest_tag#v}
        IFS='.' read -r -a version_parts <<< "$version"
        version_parts[1]=$((version_parts[1] + 1))
        new_version="v${version_parts[0]}.${version_parts[1]}"
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"
    
    - name: Generate a zip file of index-preview.py
      run: zip main.zip main.py

    - name: Create GitHub Release
      run: |
        gh release create ${{ env.new_version }} preview.zip --title "Release ${{ env.new_version }}" --notes "Automated release of main.py"
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
